function random(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
var titles = ["AI GENTE", "ORA ORA", "UGA UGA", "EU SER O MESTRE", "O LEIA"];
var canais = [
  "Nuno",
  "Black",
  "Ezequias",
  "Anony",
  "Leia",
  "JV",
  "Mestre",
  "Prefeito",
  "Kjae",
  "Klein",
  "Klevis",
  "Kobe",
  "Kobi",
  "Koby",
  "Koddi",
  "Koden",
  "Kodi",
  "Kodie",
  "Kody",
  "Kofi",
  "Kogan",
  "Kohen",
  "Kole",
  "Konan",
  "Konar",
  "Konnor",
  "Konrad",
  "Koray",
  "Korben",
  "Korbyn",
  "Korey",
  "Kori",
  "Korrin",
  "Kory",
  "Koushik",
  "Kris",
  "Krish",
  "Krishan",
  "Kriss",
  "Kristian",
  "Kristin",
  "Kristofer",
  "Kristoffer",
  "Kristopher",
  "Kruz",
  "Krzysiek",
  "Krzysztof",
  "Ksawery",
  "Ksawier",
  "Kuba",
  "Kurt",
  "Kurtis",
  "Kurtis-Jae",
  "Kyaan",
  "Kyan",
  "Kyde",
  "Kyden",
  "Kye",
  "Kyel",
  "Kyhran",
  "Kyie",
  "Kylan",
  "Kylar",
  "Kyle",
  "Kyle-Derek",
  "Kylian",
  "Kym",
  "Kynan",
  "Kyral",
  "Kyran",
  "Kyren",
  "Kyrillos",
  "Kyro",
  "Kyron",
  "Kyrran",
  "Lachlainn",
  "Lachlan",
  "Lachlann",
  "Lael",
  "Lagan",
  "Laird",
  "Laison",
  "Lakshya",
  "Lance",
  "Lancelot",
  "Landon",
  "Lang",
  "Lasse",
  "Latif",
  "Lauchlan",
  "Lauchlin",
  "Laughlan",
  "Lauren",
  "Laurence",
  "Laurie",
  "Lawlyn",
  "Lawrence",
  "Lawrie",
  "Lawson",
  "Layne",
  "Layton",
  "Lee",
  "Leigh",
  "Leigham",
  "Leighton",
  "Leilan",
  "Leiten",
  "Leithen",
  "Leland",
  "Lenin",
  "Lennan",
  "Lennen",
  "Lennex",
  "Lennon",
  "Lennox",
  "Lenny",
  "Leno",
  "Lenon",
  "Lenyn",
  "Leo",
  "Leon",
  "Leonard",
  "Leonardas",
  "Leonardo",
  "Lepeng",
  "Leroy",
  "Leven",
  "Levi",
  "Levon",
  "Levy",
  "Lewie",
  "Lewin",
  "Lewis",
  "Lex",
  "Leydon",
  "Leyland",
  "Leylann",
  "Leyton",
  "Liall",
  "Liam",
  "Liam-Stephen",
  "Limo",
  "Lincoln",
  "Lincoln-John",
  "Lincon",
  "Linden",
  "Linton",
  "Lionel",
  "Lisandro",
  "Litrell",
  "Liyonela-Elam",
  "LLeyton",
  "Lliam",
  "Lloyd",
  "Lloyde",
  "Loche",
  "Lochlan",
  "Lochlann",
  "Lochlan-Oliver",
  "Lock",
  "Lockey",
  "Logan",
  "Logann",
  "Logan-Rhys",
  "Loghan",
  "Lokesh",
  "Loki",
  "Lomond",
  "Lorcan",
  "Lorenz",
  "Lorenzo",
  "Lorne",
  "Loudon",
  "Loui",
  "Louie",
  "Louis",
  "Loukas",
  "Lovell",
  "Luc",
  "Luca",
  "Lucais",
  "Lucas",
  "Lucca",
  "Lucian",
  "Luciano",
  "Lucien",
  "Lucus",
  "Luic",
  "Luis",
  "Luk",
  "Luka",
  "Lukas",
  "Lukasz",
  "Luke",
  "Lukmaan",
  "Luqman",
  "Lyall",
  "Lyle",
  "Lyndsay",
  "Lysander",
  "Maanav",
  "Maaz",
  "Mac",
  "Macallum",
  "Macaulay",
  "Macauley",
  "Macaully",
  "Machlan",
  "Maciej",
  "Mack",
  "Mackenzie",
  "Mackenzy",
  "Mackie",
  "Macsen",
  "Macy",
  "Madaki",
  "Maddison",
  "Maddox",
  "Madison",
  "Madison-Jake",
  "Madox",
  "Mael",
  "Magnus",
  "Mahan",
  "Mahdi",
  "Mahmoud",
  "Maias",
  "Maison",
  "Maisum",
  "Maitlind",
  "Majid",
  "Makensie",
  "Makenzie",
  "Makin",
  "Maksim",
  "Maksymilian",
  "Malachai",
  "Malachi",
  "Malachy",
  "Malakai",
  "Malakhy",
  "Malcolm",
  "Malik",
  "Malikye",
  "Malo",
  "Ma'moon",
  "Manas",
  "Maneet",
  "Manmohan",
  "Manolo",
  "Manson",
  "Mantej",
  "Manuel",
  "Manus",
  "Marc",
  "Marc-Anthony",
  "Marcel",
  "Marcello",
  "Marcin",
  "Marco",
  "Marcos",
  "Marcous",
  "Marcquis",
  "Marcus",
  "Mario",
  "Marios",
  "Marius",
  "Mark",
  "Marko",
  "Markus",
  "Marley",
  "Marlin",
  "Marlon",
  "Maros",
  "Marshall",
  "Martin",
  "Marty",
  "Martyn",
  "Marvellous",
  "Marvin",
  "Marwan",
  "Maryk",
  "Marzuq",
  "Mashhood",
  "Mason",
  "Mason-Jay",
  "Masood",
  "Masson",
  "Matas",
  "Matej",
  "Mateusz",
  "Mathew",
  "Mathias",
  "Mathu",
  "Mathuyan",
  "Mati",
  "Matt",
  "Matteo",
  "Matthew",
  "Matthew-William",
  "Matthias",
  "Max",
  "Maxim",
  "Maximilian",
  "Maximillian",
  "Maximus",
  "Maxwell",
  "Maxx",
  "Mayeul",
  "Mayson",
  "Mazin",
  "Mcbride",
  "McCaulley",
  "McKade",
  "McKauley",
  "McKay",
  "McKenzie",
  "McLay",
  "Meftah",
  "Mehmet",
  "Mehraz",
  "Meko",
  "Melville",
  "Meshach",
  "Meyzhward",
  "Micah",
  "Michael",
  "Michael-Alexander",
  "Michael-James",
  "Michal",
  "Michat",
  "Micheal",
  "Michee",
  "Mickey",
  "Miguel",
  "Mika",
  "Mikael",
  "Mikee",
  "Mikey",
  "Mikhail",
  "Mikolaj",
  "Miles",
  "Millar",
  "Miller",
  "Milo",
  "Milos",
  "Milosz",
  "Mir",
  "Mirza",
  "Mitch",
  "Mitchel",
  "Mitchell",
  "Moad",
  "Moayd",
  "Mobeen",
  "Modoulamin",
  "Modu",
  "Mohamad",
  "Mohamed",
  "Mohammad",
  "Mohammad-Bilal",
  "Mohammed",
  "Mohanad",
  "Mohd",
  "Momin",
  "Momooreoluwa",
  "Montague",
  "Montgomery",
  "Monty",
  "Moore",
  "Moosa",
  "Moray",
  "Morgan",
  "Morgyn",
  "Morris",
  "Morton",
  "Moshy",
  "Motade",
  "Moyes",
  "Msughter",
  "Mueez",
  "Muhamadjavad",
  "Muhammad",
  "Muhammed",
  "Muhsin",
  "Muir",
  "Munachi",
  "Muneeb",
  "Mungo",
  "Munir",
  "Munmair",
  "Munro",
  "Murdo",
  "Murray",
  "Murrough",
  "Murry",
  "Musa",
  "Musse",
];
var comments = [
  "I like very much",
  "It was a great video!",
  "I like this video a lot!",
  "I don't like it so much :/",
  "Wow, this effect at the start of the video was great :)",
];
const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
const gradients = [
  "linear-gradient(to left, #24c6dc, #514a9d)",
  "linear-gradient(to left, #134e5e, #71b280)",
  "linear-gradient(to left, #085078, #85d8ce)",
  "linear-gradient(to left, #f12711, #f5af19)",
  "linear-gradient(to left, #f5f5f5, #c1c1c1)",
  "linear-gradient(to left, #4776e6, #8e54e9)",
  "linear-gradient(to left, #ff8008, #ffc837)",
  "linear-gradient(to left, #1d976c, #93f9b9)",
  "linear-gradient(to left, #eb3349, #f45c43)",
  "linear-gradient(to left, #dd5e89, #f7bb97)",
  "linear-gradient(to left, #4cb8c4, #3cd3ad)",
  "linear-gradient(to left, #aa076b, #61045f)",
];
function createVideos() {
  for (let viquan = 0; viquan < 20; viquan++) {
    document.querySelector("#right-side").innerHTML += `
        <div class="videos-right" style="animation-delay:${viquan * 0.1}s;">
        <div class="videos-left-part" style="background: ${gradients[random(0, gradients.length - 1)]
      };"></div>
        <div class="videos-right-part">
            <h3 class="capitalize zero-margin">${lipsum.generate(5)}</h3>
            <p class="gray-color zero-margin medium-font">${canais[random(0, canais.length - 1)]
      }</p>
            <p class="gray-color zero-margin small-font"><span class="views">${random(
        1,
        10000
      )}</span> views</p>
        </div>
        </div>`;
    console.log("kkkkkkk");
  }
}

function createComments() {
  for (let comment = 0; comment < 7; comment++) {
    document.querySelector("#comments-second-part").innerHTML += `
        <div class="comment" style="animation-delay:${Math.floor(
      comment * 0.1
    )}s;">
        <div class="flex-comment">
            <div class="circle" style="background: ${gradients[random(0, gradients.length - 1)]
      };"></div>
            <p class=r"bold" style="width: auto; border: none;">${canais[random(0, canais.length - 1)]
      }</p>
            <span class="gray-color" style="font-size: 12px;">${monthNames[random(0, 11)]
      } ${random(1, 30)} of ${random(2015, 2022)}</span>
        </div>
        <div class="comment-flex-custom">
            <p style="margin: 0px 0px !important;"><span>${lipsum.generate(
        random(5, 35)
      )}</span> 
                <br>
                <br>
            </p>
        </div>
        <div class="comment-options">
            <div class="flex-align">
                <i class="fa-solid fa-thumbs-up"></i>
                <p style="font-size: 12px; margin: 0px !important;">${random(
        1,
        1000
      )}</p>
            </div>
            <i class="fa-solid fa-thumbs-down"></i>
            <p class="bold gray-color">Answer</p>

        </div>
    </div>
    `;
    console.log("kkkkkkk");
  }
}

function background() {
  var inputcolor = document.getElementById("color").checked;
  var root = document.querySelector(":root");
  if (inputcolor) {
    root.style.setProperty("--background", "#EEEEEE");
    root.style.setProperty("--darkgray", "#F5F5F5");
    root.style.setProperty("--lightgray", "#F5F5F5");
    root.style.setProperty("--text", "#000");
    root.style.setProperty("--gray-color", "#474747");
    root.style.setProperty("--white50", "rgba(0, 0, 0, 0.2)");
  } else {
    root.style.setProperty("--background", "#171922");
    root.style.setProperty("--darkgray", "#1d2230");
    root.style.setProperty("--lightgray", "#232938");
    root.style.setProperty("--text", "#e2eafa");
    root.style.setProperty("--gray-color", "rgb(207, 207, 207)");
    root.style.setProperty("--white50", "rgba(255, 255, 255, 0.2)");
  }
}

function backgroundChecked() {
  document.getElementById("color").checked = true;
}
console.log("Funcionando");
createVideos();
createComments();
background();
